json.id combat.id
json.user_id combat.user_id
json.tab_id combat.tab_id
json.creature_name combat.creature_name
json.initiative_roll combat.initiative_roll
json.health combat.health
json.status combat.status
json.created_at combat.created_at
json.updated_at combat.updated_at